ALTER TABLE "Movement"
ADD COLUMN "totalWeightGrams" DOUBLE PRECISION,
ADD COLUMN "tareWeightGrams" DOUBLE PRECISION,
ADD COLUMN "netWeightGrams" DOUBLE PRECISION,
ADD COLUMN "unitWeightGrams" DOUBLE PRECISION;

ALTER TABLE "PutawayCaptureRequest"
ADD COLUMN "totalWeightGrams" DOUBLE PRECISION,
ADD COLUMN "tareWeightGrams" DOUBLE PRECISION,
ADD COLUMN "netWeightGrams" DOUBLE PRECISION,
ADD COLUMN "unitWeightGrams" DOUBLE PRECISION;

ALTER TABLE "CameraCaptureJob"
ADD COLUMN "totalWeightGrams" DOUBLE PRECISION;
